""" ============================== Fiats ============================== """
FIAT_USD = "USD"
FIAT_CAD = "CAD"
FIAT_EUR = "EUR"

""" ============================== Cryptos ============================== """
CARDANO = "ADA"

""" ============================== Field Names ============================== """
EPOCH = "Epoch"
DATE = "Date"
START_DATE = "Start Date"
END_DATE = "End Date"
AMOUNT = "Amount ({ticker})"
TXN_FEE = "TXN Fee ({currency})"
PRICE_USD = "Average Price (USD)"
VALUE_USD = "Value (USD)"
